### ISSUE TITLE
Document how to get and install ddc_pub

### ISSUE THREAD

**Issue by cthoyt** [Dierme/latent-gan#2]

**Comment by Dierme** [comment]
ddc_pub is the autoencoder that is currently a part of an unpublished work by different authors at AstraZeneca. In it's place any autoencoder can be used to achieve the same result. I will document and create a stub soon to illustrate what methods should be implemented for the code to run.

**Comment by WhatAShot** [comment]
@Dierme Is it necessary to install ddc_pub to re-implementate the results reported in paper?

**Comment by Dierme** [comment]
@WhatAShot I am no longer working on that project.
@SeemonJ could you please answer all questions regarding ddc_puc?

**Comment by cthoyt** [comment]
Would be nice to put a disclaimer on this repository if a fix isn't likely to come soon

**Comment by SeemonJ** [comment]
This has been added in a recent commit, sorry for the delay.
